name = "edusiahub-ai"
main = "functions/api/ai/generate-alternative.js"
compatibility_date = "2024-01-01"

[vars]
# Add your environment variables here

# Add your secrets using: wrangler secret put GEMINI_API_KEY 